// Copyright (C) 1991-2010 Altera Corporation
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and its AMPP partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, Altera MegaCore Function License 
// Agreement, or other applicable license agreement, including, 
// without limitation, that your use is for the sole purpose of 
// programming logic devices manufactured by Altera and sold by 
// Altera or its authorized distributors.  Please refer to the 
// applicable agreement for further details.


// Generated by Quartus II Version 10.0 (Build Build 218 06/27/2010)
// Created on Fri Oct 18 15:23:02 2019

21mux 21mux_inst
(
	.A(A_sig) ,	// input  A_sig
	.B(B_sig) ,	// input  B_sig
	.S(S_sig) ,	// input  S_sig
	.Y(Y_sig) 	// output  Y_sig
);

